### ISSUE TITLE
Kitchen conv(erge) gives AzureOperationError

### ISSUE THREAD

**Issue by iiro** [pendrica/kitchen-azurerm#24]
Hi,

I tried to follow all the setup instuctions, but I get this (in TK log file):

```
# cat .kitchen/logs/kitchen.log
I, [2016-03-18T23:16:00.544922 #82662]  INFO -- Kitchen: -----> Starting Kitchen (v1.6.0)
I, [2016-03-18T23:16:01.245511 #82662]  INFO -- Kitchen: -----> Creating <policy-web-apache2-ubuntu-1404>...
E, [2016-03-18T23:16:02.858463 #82662] ERROR -- Kitchen: ------Exception-------
E, [2016-03-18T23:16:02.858659 #82662] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2016-03-18T23:16:02.858815 #82662] ERROR -- Kitchen: Message: Failed to complete #create action: [MsRestAzure::AzureOperationError]
E, [2016-03-18T23:16:02.858883 #82662] ERROR -- Kitchen: ---Nested Exception---
E, [2016-03-18T23:16:02.858915 #82662] ERROR -- Kitchen: Class: MsRestAzure::AzureOperationError
E, [2016-03-18T23:16:02.858956 #82662] ERROR -- Kitchen: Message: MsRestAzure::AzureOperationError
E, [2016-03-18T23:16:02.858982 #82662] ERROR -- Kitchen: ------Backtrace-------
E, [2016-03-18T23:16:02.859005 #82662] ERROR -- Kitchen: /Users/iiro/.chefdk/gem/ruby/2.1.0/gems/azure_mgmt_resources-0.1.1/lib/azure_mgmt_resources/resource_groups.rb:305:in `block in begin_create_or_update'
E, [2016-03-18T23:16:02.859031 #82662] ERROR -- Kitchen: /Users/iiro/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-1.0.1/lib/concurrent/promise.rb:496:in `call'
E, [2016-03-18T23:16:02.859054 #82662] ERROR -- Kitchen: /Users/iiro/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-1.0.1/lib/concurrent/promise.rb:496:in `block in on_fulfill'
E, [2016-03-18T23:16:02.859078 #82662] ERROR -- Kitchen: /Users/iiro/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-1.0.1/lib/concurrent/executor/safe_task_executor.rb:24:in `call'
E, [2016-03-18T23:16:02.859103 #82662] ERROR -- Kitchen: /Users/iiro/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-1.0.1/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
E, [2016-03-18T23:16:02.859127 #82662] ERROR -- Kitchen: /Users/iiro/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-1.0.1/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
E, [2016-03-18T23:16:02.859169 #82662] ERROR -- Kitchen: /Users/iiro/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-1.0.1/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
E, [2016-03-18T23:16:02.859204 #82662] ERROR -- Kitchen: /Users/iiro/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-1.0.1/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
E, [2016-03-18T23:16:02.859228 #82662] ERROR -- Kitchen: /Users/iiro/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-1.0.1/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
E, [2016-03-18T23:16:02.859252 #82662] ERROR -- Kitchen: /Users/iiro/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-1.0.1/lib/concurrent/promise.rb:526:in `block in realize'
E, [2016-03-18T23:16:02.859276 #82662] ERROR -- Kitchen: /Users/iiro/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-1.0.1/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `call'
E, [2016-03-18T23:16:02.859299 #82662] ERROR -- Kitchen: /Users/iiro/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-1.0.1/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
E, [2016-03-18T23:16:02.859323 #82662] ERROR -- Kitchen: /Users/iiro/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-1.0.1/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
E, [2016-03-18T23:16:02.859443 #82662] ERROR -- Kitchen: /Users/iiro/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-1.0.1/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
E, [2016-03-18T23:16:02.859514 #82662] ERROR -- Kitchen: /Users/iiro/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-1.0.1/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
E, [2016-03-18T23:16:02.859548 #82662] ERROR -- Kitchen: /Users/iiro/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-1.0.1/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
E, [2016-03-18T23:16:02.859574 #82662] ERROR -- Kitchen: /Users/iiro/.chefdk/gem/ruby/2.1.0/gems/concurrent-ruby-1.0.1/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
E, [2016-03-18T23:16:02.859599 #82662] ERROR -- Kitchen: ----------------------
```

Any ideas? Credential-file should be ok also.

I'm new to Azure to this can be easily an user error.

**Comment by stuartpreston** [comment]
Could you post your kitchen.yml file please? (feel free to take out the subscription ID and any sensitive values).

**Comment by stuartpreston** [comment]
I can repro this failure if I changed the driver_config location to a value that was not valid for my subscription.

```
driver_config:
  location: 'typod location'
```

Could that be the problem here?

**Comment by iiro** [comment]
Hi,

I tried to follow up your example, only changing the necessary ones - here's the Kitchen YAML:

```
---
driver:
  name: azurerm

driver_config:
  subscription_id: 'MY_SUBSCRIPTION_ID_MATCHING_IN_CREDENTIALS_FILE'
  location: 'West Europe'
  machine_size: 'Standard_D1'

transport:
  name: rsync
  username: ubuntu
  ssh_key: ~/.ssh/azure

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver_config:
      image_urn: Canonical:UbuntuServer:14.04.3-LTS:latest
      vm_name: trusty-vm

suites:
  - name: policy_web_apache2
    provisioner:
      policyfile: policies/web_apache2.rb
    ## Example of how to use remote InSpec profiles.
    ## Requires Test-Kitchen 1.6.0+ and kitchen-inspec RubyGem version 0.12.4+
    #verifier:
    #  inspec_tests:
    #    - https://github.com/nathenharvey/tmp_compliance_profile
  - name: policy_web_nginx
    provisioner:
      policyfile: policies/web_nginx.rb
```

Can this be an error in my ~/.azure/credentials...? I tried to follow your example there as well...
