### ISSUE TITLE
kitchen create fails with permission error

### ISSUE THREAD

**Issue by mattstratton** [pendrica/kitchen-azurerm#37]
I'm using the latest `kitchen-azurerm`.

Here's my `.kitchen.yml`
```
---
driver:
  name: azurerm

driver_config:
  subscription_id: '950ca109-6d5b-4699-81f1-98eef6cd2faf'
  location: 'West Europe'
  machine_size: 'Standard_D1'

transport:
  ssh_key: ~/.ssh/id_kitchen-azurerm

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
    driver_config:
      image_urn: Canonical:UbuntuServer:14.04.4-LTS:latest
      vm_name: trusty-vm

suites:
  - name: default
    run_list:
      - recipe[azure_linux_test::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
```

My `~/.azure/credentials` file looks like this (password redacted):

```
[950ca109-6d5b-4699-81f1-98eef6cd2faf]
client_id = "ed09fd66-23c9-4a9f-925d-54a0dc83430a"
client_secret = "*******"
tenant_id = "205db08b-5970-49b4-aa7d-3eb537878eee"
```

I have given the service principal "Owner" rights on the subscription (I had tried with Contributor before, but it didn't work):

```
 ~/src/bluth_repo/cookbooks/azure_linux_test/ [master] azure role assignment list
info:    Executing command role assignment list
+ Searching for role assignments
data:    RoleAssignmentId     : /subscriptions/950ca109-6d5b-4699-81f1-98eef6cd2faf/providers/Microsoft.Authorization/roleAssignments/bc54877b-f09b-471d-aa9c-ca5b379354c0
data:    RoleDefinitionName   : Owner
data:    RoleDefinitionId     : 8e3af657-a8ff-443c-a75c-2fe8c4bcb635
data:    Scope                : /subscriptions/950ca109-6d5b-4699-81f1-98eef6cd2faf
data:    Display Name         : testkitchen
data:    SignInName           : undefined
data:    ObjectId             : 5c735b55-dd39-46e9-b8ef-065faaf3d374
data:    ObjectType           : ServicePrincipal
data:
info:    role assignment list command OK
```

And I get a security error on `kitchen converge`

```
 ~/src/bluth_repo/cookbooks/azure_linux_test/ [master] kitchen create
Ignoring unf_ext-0.0.7.2 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.2
-----> Starting Kitchen (v1.13.2)
-----> Creating <default-ubuntu-1404>...
       Creating Resource Group: kitchen-default-ubuntu-1404-20161110T140900
       Creating deployment: deploy-9224c627a7421859
       Adding public key from /Users/mattstratton/.ssh/id_kitchen-azurerm.pub to the deployment.
       Resource Template deployment reached end state of 'Failed'.
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [{"error"=>{"code"=>"AuthorizationFailed", "message"=>"The client '5c735b55-dd39-46e9-b8ef-065faaf3d374' with object id '5c735b55-dd39-46e9-b8ef-065faaf3d374' does not have authorization to perform action 'Microsoft.Network/virtualNetworks/write' over scope '/subscriptions/950ca109-6d5b-4699-81f1-98eef6cd2faf/resourcegroups/kitchen-default-ubuntu-1404-20161110T140900/providers/Microsoft.Network/virtualNetworks/vnet'."}}] on default-ubuntu-1404
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

I am able to manually create items inside the portal, so I know my subscription is fine (it also shows as Active).

What am I missing?
