### ISSUE TITLE
WinRM timeout in test-kitchen on Windows

### ISSUE THREAD

**Issue by glennmate** [pendrica/kitchen-azurerm#41]
I'm currently using a homegrown cookbook to install Nodejs for windows. I can then use a community LWRP to install npm packages on Windows.  To cover my bases, I've linked my issue on the community cookbook as well here: https://github.com/redguide/nodejs/issues/148

Using test-kitchen `kitchen converge -l debug`, when using resource `nodejs_npm 'gulp'` I find the debug output:
```
       [2016-12-09T07:24:40+00:00] DEBUG: Providers for generic execute resource enabled on node include: [Chef::Provider::Execute]
       [2016-12-09T07:24:40+00:00] DEBUG: Provider for action run on resource execute[install NPM package gulp] is Chef::Provider::Execute

             [execute] npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
                npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
                npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls gr
aceful-fs' to find it in the tree.
                C:\Users\azure\AppData\Roaming\npm\gulp -> C:\Users\azure\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js
                C:\Users\azure\AppData\Roaming\npm
                `-- gulp@3.9.1

D      [WinRM] retrying receive request after timeout
```

If I let it wait, I'll just get the last line `[WinRM]` error forever.

When logging in locally and running the same command `npm install -g gulp` I get the below output:
```
PS C:\Users\azure> npm install -g gulp
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update t
o graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
C:\Users\azure\AppData\Roaming\npm\gulp -> C:\Users\azure\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js
C:\Users\azure\AppData\Roaming\npm
`-- gulp@3.9.1

PS C:\Users\azure>
```

Outputs are the same (and the command runs 100% successfully), it just seems that WinRM doesn't release the shell back to test-kitchen after npm is done installing. Seen this issue before? It may be nodejs specific, but I'm curious if this is an issue with WinRM not letting test-kitchen know that the resource is done. 

For good merit, here's my `.kitchen.yml` file:
```
---
driver:
  name: azurerm

driver_config:
  subscription_id: "123-guid-goes-here-456"
  location: "East US"
  machine_size: "Standard_DS1"

provisioner:
  name: chef_zero

platforms:
  - name: windows2012-r2
    driver_config:
      image_urn: MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest
    transport:
      name: winrm
      elevated: true

suites:
  - name: default
    run_list:
      - recipe[nap-nodejs::default]
    attributes:
```
