### ISSUE TITLE
subscription_id should not be mandatory for .kitchen.yml

### ISSUE THREAD

**Issue by vinyar** [pendrica/kitchen-azurerm#6]
Bug: All of the settings for azure are pulled in from the ~/.azure/credentials file.

Subscription ID is one of the settings. The default behavior of the azure-cli is to use the top Subscription if there are multiple subscriptions and default one is not specified.

Current expectation
```
---
driver:
  name: azurerm

driver_config:
  subscription_id: '43e53945-f02b-4269-8854-ad7dd14ac6f2'
  location: 'West Europe'
  machine_size: 'Standard_D1'
```

Expected behavior: subscription id is pulled from credentials file.
```
---
driver:
  name: azurerm

driver_config:
  location: 'West Europe'
  machine_size: 'Standard_D1'
```
